---
# tasks file for awsinstance

- name: "provisioning OS on AWS using Ansible"
  ec2:
       key_name: "mykey1234"
       instance_type: "t2.micro"
       image: "ami-0ebc1ac48dfd14136"
       wait: yes
       count: 1
       instance_tags:
          Name: aws_ansible_ec2
       vpc_subnet_id: "subnet-2a292542"
       assign_public_ip: yes
       region: "ap-south-1"
       state: present
       group_id: "sg-a1f699c5"
       aws_access_key: "{{	myuser	}}"
       aws_secret_key: "{{	mypass	}}"
  register: X
- debug:
     var:  X.instances[0].public_ip
